name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Verificar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Atualizar o README
      - name: Update README
        run: |
          echo "Última atualização: $(date)" >> README.md

      # Commit e push das alterações
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Atualizado automaticamente pelo GitHub Actions"
          git push
